//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicaly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alamat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alamat()
        {
            this.HeaderTransactions = new HashSet<HeaderTransaction>();
        }
    
        public long Id { get; set; }
        public string LabelAlamat { get; set; }
        public string NamaPenerima { get; set; }
        public string NoHandphone { get; set; }
        public string KotaKecamatan { get; set; }
        public Nullable<int> KodePost { get; set; }
        public string Alamat1 { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeaderTransaction> HeaderTransactions { get; set; }
    }
}
