//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicaly.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Konsultasis = new HashSet<Konsultasi>();
        }
    
        public long Id { get; set; }
        public Nullable<long> NoKTP { get; set; }
        public string Nama { get; set; }
        public string Email { get; set; }
        public string Alamat { get; set; }
        public string NoHandphone { get; set; }
        public string Password { get; set; }
        public string Alumni { get; set; }
        public Nullable<int> Pengalaman { get; set; }
        public string STR { get; set; }
        public string SIP { get; set; }
        public Nullable<long> SpesialisId { get; set; }
        public string FotoProfile { get; set; }

        public HttpPostedFileBase ImageUpload { get; set; }

        public virtual Spesiali Spesiali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konsultasi> Konsultasis { get; set; }
    }
}
