//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicaly.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class HeaderTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeaderTransaction()
        {
            this.DetailTransactions = new HashSet<DetailTransaction>();
        }
    
        public int Id { get; set; }
        public Nullable<long> AlamatId { get; set; }
        public string TransactionDate { get; set; }
        public string PaymentType { get; set; }
        public string BankName { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNumber { get; set; }
        public string TransferNominal { get; set; }
        public string TransferProof { get; set; }
        public string Status { get; set; }
        public Nullable<long> TotalHarga { get; set; }

        public HttpPostedFileBase ImageUpload { get; set; }
        public virtual Alamat Alamat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTransaction> DetailTransactions { get; set; }
    }
}
