//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicaly.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Konsultasi
    {
        public long Id { get; set; }
        public string Nama { get; set; }
        public string Email { get; set; }
        public string Judul { get; set; }
        public Nullable<long> SpesialisId { get; set; }
        public string Detail { get; set; }
        public string Jawaban { get; set; }
        public Nullable<long> DoktorId { get; set; }
        public string FilePendukung { get; set; }
        public Nullable<int> Status { get; set; }

        public HttpPostedFileBase ImageUpload { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Spesiali Spesiali { get; set; }
    }
}
